const data = {
  products: [
    {
      _id: "1",
      name: "Nike Slim shirt",
      category: "Shirts",
      image: "p1.jpg",
      price: 120,
      brand: "Nike",
      rating: 4.5,
      numReview: 10,
      description: "High quality products",
    },
    {
      _id: "2",
      name: "adidas fit shirt",
      category: "Shirts",
      image: "p1.jpg",
      price: 280,
      brand: "Addidas",
      rating: 4.5,
      numReview: 10,
      description: "High quality products",
    },
    {
      _id: "3",
      name: "Nike Slim shirt",
      category: "Shirts",
      image: "p1.jpg",
      price: 120,
      brand: "Nike",
      rating: 3,
      numReview: 78,
      description: "High quality products",
    },
    {
      _id: "4",
      name: "Nike Slim shirt",
      category: "Shirts",
      image: "p1.jpg",
      price: 120,
      brand: "Nike",
      rating: 3,
      numReview: 10,
      description: "High quality products",
    },
    {
      _id: "5",
      name: "Nike Slim shirt",
      category: "Shirts",
      image: "p1.jpg",
      price: 120,
      brand: "Nike",
      rating: 4,
      numReview: 17,
      description: "High quality products",
    },
    {
      _id: "6",
      name: "Nike Slim shirt",
      category: "Shirts",
      image: "p1.jpg",
      price: 120,
      brand: "Nike",
      rating: 4.5,
      numReview: 10,
      description: "High quality products",
    },
  ],
};

module.exports = data;
